### ISSUE TITLE
Нарисовать летнюю локацию

### ISSUE THREAD

**Issue by alchemmist** [markmelix/corpse#4]
Совместно нарисовать летнюю локацию, используя Tiled. На локации должны быть:

### Ground

- Трава
- Земля
- Асфальт
- Дорога

P.S.
Воду наверное не стоит использовать, так как придётся добавлять в игру логику взаимодействия с ней.
Песок можно, но вряд ли он органично впишется.

### Objects

- Кусты(разных видов)
- Деревья
- Пни
- Ящики 
- Камни
- Предметы 
    - Еда
    - Медикаменты
    - Оружие
    - Патроны
    - Броня
- Обломки самолётов
- Разбитые машины
- Бочки
- Дома + интерьер
- Стены из мешков

### Creatures

- 

### Интерфейс

**Comment by markmelix** [comment]
Тайлы воды можно использовать, просто сделаем, что персонаж не сможет по ним ходить. Так можно создать "эффект острова", ограничив карту клетками непроходимой воды.

**Comment by markmelix** [comment]
Ещё нужно зарефакторить всю папку resources
